import Head from 'next/head';
import { About, GetStarted, Hero, Collaborators, Awards } from '../sections';
import { Slider } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <About />
        <GetStarted />
        <Awards />
        <Slider />
        <Collaborators />
        <div className="bg-primary-black h-[.8rem]" />
      </main>
    </>
  );
}
